services:
  app:
    build:
      context: .
      target: prod
      dockerfile: docker/Dockerfile
    container_name: wmanager_app_prod
    image: wmanager:latest
    user: "www-data:www-data"
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - data:/var/www/storage
    networks:
      - net

  queue-worker:
    image: wmanager:latest
    container_name: wmanager_app_queue
    restart: unless-stopped
    user: "www-data:www-data"
    env_file:
      - .env.prod
    volumes:
      - data:/var/www/storage
    command: php /var/www/artisan queue:work --verbose --tries=3 --timeout=90
    depends_on:
      - app
    networks:
      - net

  web:
    build:
      context: .
      target: nginx
      dockerfile: docker/Dockerfile
    container_name: wmanager_nginx_prod
    image: wmanager_nginx:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - app
    networks:
      - net

networks:
  net:
    driver: bridge
  
volumes:
  data: